name: Tests

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install
      - run: npm run test

      - uses: codecov/codecov-action@v1
        with:
          files: ./coverage/coverage-final.json
          fail_ci_if_error: true
