name: Tests

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2.4.2

      - name: Setup Node environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm install

      - name: Run test suite
        run: npm run test

      - name: Upload results to Codecov.
        uses: codecov/codecov-action@v3.1.0
        with:
          files: ./coverage/coverage-final.json
          fail_ci_if_error: true
